2021-02-22 16:51:45,907 INFO: Microblog startup [in /Users/alessandrofranca/PycharmProjects/VirtusAggregation/WebAppOptimizer/app/__init__.py:82]
2021-02-24 11:25:26,187 INFO: Microblog startup [in /Users/alessandrofranca/PycharmProjects/VirtusAggregation/WebAppOptimizer/app/__init__.py:82]
2021-02-24 11:25:54,589 ERROR: Exception on /user/admin [GET] [in /Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 466, in _cached_result_processor
    return dialect._type_memos[self][coltype]
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/weakref.py", line 383, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7fdd5f2b7360; to 'JSON' at 0x7fdd5d864220>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alessandrofranca/PycharmProjects/VirtusAggregation/WebAppOptimizer/app/main/routes.py", line 184, in user
    configurations = user.configurations.order_by(Configuration.timestamp.desc()).paginate(
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 491, in paginate
    items = self.limit(per_page).offset((page - 1) * per_page).all()
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1048, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1204, in _execute_context
    result = context.get_result_proxy()
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 877, in get_result_proxy
    return result.ResultProxy(self)
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 653, in __init__
    self._init_metadata()
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 682, in _init_metadata
    self._metadata = ResultMetaData(self, cursor_description)
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 213, in __init__
    raw = self._merge_cursor_description(
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 368, in _merge_cursor_description
    return [
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 373, in <listcomp>
    context.get_result_processor(
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 840, in get_result_processor
    return type_._cached_result_processor(self.dialect, coltype)
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 472, in _cached_result_processor
    d[coltype] = rp = d['impl'].result_processor(dialect, coltype)
  File "/Users/alessandrofranca/opt/anaconda3/envs/EnergyManagementEnv/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 2069, in result_processor
    json_deserializer = dialect._json_deserializer or json.loads
AttributeError: 'SQLiteDialect_pysqlite' object has no attribute '_json_deserializer'
